-- Migration 030: Add image_source column to posts table
-- Tracks the origin of a post's image:
--   uploaded    — file uploaded via content form
--   generated   — dynamic image generated by ImageService::generateFromTemplate()
--   url_fetched — reserved for future use
-- NULL = text-only post or image source not yet determined

ALTER TABLE `posts`
  ADD COLUMN `image_source` ENUM('uploaded', 'generated', 'url_fetched') NULL DEFAULT NULL
  AFTER `image_filename`;
